# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://torontoriichi.club'
baseurl: ''
lang: en-CA
title: 'Toronto Riichi Club'
description: 'To ron, to riichi.'
permalink: pretty
logo: "/assets/logos/logo@52px.png"
repo: "https://github.com/toronto-riichi-club/toronto-riichi-club.github.io"
email: "contact@torontoriichi.club"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
#  About: /about/
#  Blog: /blog/
  Contact: /contact/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
#collections:
#  posts:
#    title: Posts
#    output: true
#    description: "My thoughts and ideas"
#    feature_text: |
#      Welcome to my blog
#    feature_image: "https://picsum.photos/2560/600?image=866"
